### PR TITLE
add test and code for gauge values

### PR DESCRIPTION
**Pull request by luxflux**
Yeah, title says it :)

### CODE REVIEW

**Comment by bvandenbos** [comment]
Thanks!

**Comment by luxflux** [comment]
Would be cool if you could push a new gem version... :)

**Comment by bvandenbos** [comment]
Yeah.  No problem.

On Jun 11, 2012, at 4:24 AM, Raffael Schmid
reply@reply.github.com
wrote:

**Comment by bvandenbos** [comment]
Pushed.  Thanks.

**Comment by luxflux** [comment]
Thanks!

**Pull request merged**
